[package]
name          = "shared"
license       = "MIT"
repository    = "https://github.com/pmqueiroz/import-holmes.git"
version       = "0.1.0"

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
