name: Pull Checks

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
          run_install: true
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
          run_install: false
      - name: lint
        run: pnpm lint src
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
          run_install: false
      - name: test
        run: pnpm test
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
          run_install: false
      - name: build
        run: pnpm build
